name: melos_version_test
publish_to: none
environment:
  sdk: '>=3.6.1 <4.0.0'

workspace:
  - package_a
  - package_b
  - package_c

melos:
  useRootAsPackage: false
  command:
    version:
      branch: main
      includeCommitId: true
      # updateGitTagRefs: true
      releaseUrl: true
    bootstrap:
      environment:
        sdk: '>=3.6.1 <4.0.0'
        flutter: '>=3.27.3 <4.0.0'

dev_dependencies: 
  melos: ^7.0.0-dev.8